CREATE SEQUENCE TASK_SEQ START WITH 1 INCREMENT BY 50;

CREATE TABLE TASK
(
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    status      VARCHAR(50)
);
